[build-system]
requires = ["uv_build >= 0.12.1, <0.13.0"]
build-backend = "uv_build"

[project]
name = "myTomorrows_a2"
version = "0.1.0"
dependencies = [
    "httpx",
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "pydantic",
    "pydantic-settings",
    "pymysql",
    "python-dotenv",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff.lint]
ignore = ["B008"]  # Depends()/Query()/Path() in defaults
